"""init

Revision ID: 0dada81b9c47
Revises: d36a6c8f26c1
Create Date: 2025-08-30 23:08:51.053315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dada81b9c47'
down_revision: Union[str, Sequence[str], None] = 'd36a6c8f26c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activities_classroom_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('classrooms_teacher_id_fkey'), 'classrooms', type_='foreignkey')
    op.drop_constraint(op.f('classrooms_period_id_fkey'), 'classrooms', type_='foreignkey')
    op.create_foreign_key(None, 'classrooms', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'classrooms', 'periods', ['period_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('grades_student_id_fkey'), 'grades', type_='foreignkey')
    op.drop_constraint(op.f('grades_activity_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('periods_teacher_id_fkey'), 'periods', type_='foreignkey')
    op.create_foreign_key(None, 'periods', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('students_classroom_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_classroom_id_fkey'), 'students', 'classrooms', ['classroom_id'], ['id'])
    op.drop_constraint(None, 'periods', type_='foreignkey')
    op.create_foreign_key(op.f('periods_teacher_id_fkey'), 'periods', 'teachers', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_activity_id_fkey'), 'grades', 'activities', ['activity_id'], ['id'])
    op.create_foreign_key(op.f('grades_student_id_fkey'), 'grades', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.create_foreign_key(op.f('classrooms_period_id_fkey'), 'classrooms', 'periods', ['period_id'], ['id'])
    op.create_foreign_key(op.f('classrooms_teacher_id_fkey'), 'classrooms', 'teachers', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_classroom_id_fkey'), 'activities', 'classrooms', ['classroom_id'], ['id'])
    # ### end Alembic commands ###
