"""init

Revision ID: d36a6c8f26c1
Revises: 
Create Date: 2025-08-30 23:02:08.559355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36a6c8f26c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activities_classroom_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'classrooms', ['classroom_id'], ['id'])
    op.drop_index(op.f('fki_classrooms_period_id_fkey'), table_name='classrooms')
    op.drop_constraint(op.f('classrooms_period_id_fkey'), 'classrooms', type_='foreignkey')
    op.drop_constraint(op.f('classrooms_teacher_id_fkey'), 'classrooms', type_='foreignkey')
    op.create_foreign_key(None, 'classrooms', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'classrooms', 'periods', ['period_id'], ['id'])
    op.drop_constraint(op.f('unique_student_activity'), 'grades', type_='unique')
    op.drop_constraint(op.f('grades_activity_id_fkey'), 'grades', type_='foreignkey')
    op.drop_constraint(op.f('grades_student_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'activities', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'])
    op.drop_constraint(op.f('fk_teacher'), 'periods', type_='foreignkey')
    op.create_foreign_key(None, 'periods', 'teachers', ['teacher_id'], ['id'])
    op.drop_constraint(op.f('students_classroom_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'classrooms', ['classroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_classroom_id_fkey'), 'students', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'periods', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teacher'), 'periods', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_student_id_fkey'), 'grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('grades_activity_id_fkey'), 'grades', 'activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('unique_student_activity'), 'grades', ['student_id', 'activity_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.create_foreign_key(op.f('classrooms_teacher_id_fkey'), 'classrooms', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('classrooms_period_id_fkey'), 'classrooms', 'periods', ['period_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('fki_classrooms_period_id_fkey'), 'classrooms', ['period_id'], unique=False)
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_classroom_id_fkey'), 'activities', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
